version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: minipm-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=minipm
      - MONGO_INITDB_ROOT_PASSWORD=minipmpassword
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data:
    driver: local